In [5]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url6 = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#1956"
response6 = requests.get(url6)
soup6 = BeautifulSoup(response6.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response6.status_code}')

# Get all tables in wikitable class
tables6 = soup6.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables6)}')

# Load the 1948 polling table manually by index
df_6 = pd.read_html(str(tables6[5]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df_6.head(250))

# Rename candidate columns for consistency
df_6 = df_6.rename(columns={
    df_6.columns[2]: 'Democratic',
    df_6.columns[1]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df_6.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df_6.dtypes)

# Convert percentage strings to floats
df_6['Democratic'] = df_6['Democratic'].str.replace('%', '').astype(float)
df_6['Republican'] = df_6['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df_6.dtypes)

# Add calculated columns
df_6['Poll_Leading_Margin'] = abs(df_6['Democratic'] - df_6['Republican'])
df_6['Poll_Leader'] = (df_6['Republican'] > df_6['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df_6.head(250))

print(list(df_6.columns))

# Drop the extra columns
df_6 = df_6.drop(columns='Month')
#df_6 = df_6.drop(columns=['Henry A. Wallace (Progressive)\xa0%', 'Strom Thurmond (Dixiecrat)\xa0%'])

print('\nDropped Extra Columns:')
display(df_6.head(250))

# Drop final summary rows (row 12 and 13)
df_6 = df_6.drop(index=[12, 13])
df_6.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (12 & 13):')
display(df_6.tail())

print('\nFinal dtypes:')
display(df_6.dtypes)

# Add year column at the beginning
df_6.insert(0, 'year', 1956)

df_6 = df_6.dropna(subset=['Democratic', 'Republican'], how='all')
df_6 = df_6.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df_6.head(250))

print('\nNumber of Nulls left:')
display(df_6.isnull().sum())

df_6.to_csv("1956_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12119/2773320518.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_6 = pd.read_html(str(tables6[5]))[0]

,Month,Dwight D. Eisenhower (R) %,Adlai Stevenson II (D) %
0,December 1955/January 1956,61%,35%
1,February/March,63%,33%
2,April/May,61%,37%
3,April/May,62%,33%
4,April/May,62%,35%
5,June/July,62%,35%
6,June/July,61%,37%
7,August/September,52%,41%
8,August/September,52%,41%
9,August/September,52%,40%
10,October/November,51%,41%
11,October/November,59%,40%
12,Actual result,57.37%,41.97%
13,Difference between actual result and final poll,-1.63%,+1.97%

Renamed Columns Table Preview:

                                              Month Republican Democratic
0                        December 1955/January 1956        61%        35%
1                                    February/March        63%        33%
2                                         April/May        61%        37%
3                                         April/May        62%        33%
4                                         April/May        62%        35%
5                                         June/July        62%        35%
6                                         June/July        61%        37%
7                                  August/September        52%        41%
8                                  August/September        52%        41%
9                                  August/September        52%        40%
10                                 October/November        51%        41%
11                                 October/November        59%        40%
12                                    Actual result     57.37%     41.97%
13  Difference between actual result and final poll     -1.63%     +1.97%

Data Types Before Conversion:

Month         object
Republican    object
Democratic    object
dtype: object

Data Types After Conversion:

Month          object
Republican    float64
Democratic    float64
dtype: object

Table with New Columns:

,Month,Republican,Democratic,Poll_Leading_Margin,Poll_Leader
0,December 1955/January 1956,61.00,35.00,26.0,1
1,February/March,63.00,33.00,30.0,1
2,April/May,61.00,37.00,24.0,1
3,April/May,62.00,33.00,29.0,1
4,April/May,62.00,35.00,27.0,1
5,June/July,62.00,35.00,27.0,1
6,June/July,61.00,37.00,24.0,1
7,August/September,52.00,41.00,11.0,1
8,August/September,52.00,41.00,11.0,1
9,August/September,52.00,40.00,12.0,1
10,October/November,51.00,41.00,10.0,1
11,October/November,59.00,40.00,19.0,1
12,Actual result,57.37,41.97,15.4,1
13,Difference between actual result and final poll,-1.63,1.97,3.6,0

['Month', 'Republican', 'Democratic', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0        61.00       35.00                 26.0            1
1        63.00       33.00                 30.0            1
2        61.00       37.00                 24.0            1
3        62.00       33.00                 29.0            1
4        62.00       35.00                 27.0            1
5        62.00       35.00                 27.0            1
6        61.00       37.00                 24.0            1
7        52.00       41.00                 11.0            1
8        52.00       41.00                 11.0            1
9        52.00       40.00                 12.0            1
10       51.00       41.00                 10.0            1
11       59.00       40.00                 19.0            1
12       57.37       41.97                 15.4            1
13       -1.63        1.97                  3.6            0

After Dropping Final Rows (12 & 13):

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
7         52.0        41.0                 11.0            1
8         52.0        41.0                 11.0            1
9         52.0        40.0                 12.0            1
10        51.0        41.0                 10.0            1
11        59.0        40.0                 19.0            1

Final dtypes:

Republican             float64
Democratic             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0   1956        61.0        35.0                 26.0            1
1   1956        63.0        33.0                 30.0            1
2   1956        61.0        37.0                 24.0            1
3   1956        62.0        33.0                 29.0            1
4   1956        62.0        35.0                 27.0            1
5   1956        62.0        35.0                 27.0            1
6   1956        61.0        37.0                 24.0            1
7   1956        52.0        41.0                 11.0            1
8   1956        52.0        41.0                 11.0            1
9   1956        52.0        40.0                 12.0            1
10  1956        51.0        41.0                 10.0            1
11  1956        59.0        40.0                 19.0            1

Number of Nulls left:

year                   0
Republican             0
Democratic             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64