In [2]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url8 = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#1964"
response8 = requests.get(url8)
soup8 = BeautifulSoup(response8.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response8.status_code}')

# Get all tables in wikitable class
tables8 = soup8.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables8)}')

# Load the 1960 polling table manually by index
df_8 = pd.read_html(str(tables8[7]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df_8.head(250))

# Rename candidate columns for consistency
df_8 = df_8.rename(columns={
    df_8.columns[1]: 'Democratic',
    df_8.columns[2]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df_8.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df_8.dtypes)

# Convert percentage strings to floats
df_8['Democratic'] = df_8['Democratic'].str.replace('%', '').astype(float)
df_8['Republican'] = df_8['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df_8.dtypes)

# Add calculated columns
df_8['Poll_Leading_Margin'] = abs(df_8['Democratic'] - df_8['Republican'])
df_8['Poll_Leader'] = (df_8['Republican'] > df_8['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df_8.head(250))

print(list(df_8.columns))

# Drop the extra columns
df_8 = df_8.drop(columns='Month')
#df_8 = df_8.drop(columns=['Henry A. Wallace (Progressive)\xa0%', 'Strom Thurmond (Dixiecrat)\xa0%'])

print('\nDropped Extra Columns:')
display(df_8.head(250))

# Drop final summary rows (row 9 and 10)
df_8 = df_8.drop(index=[9, 10])
df_8.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (9 & 10):')
display(df_8.tail())

print('\nFinal dtypes:')
display(df_8.dtypes)

# Add year column at the beginning
df_8.insert(0, 'year', 1964)

df_8 = df_8.dropna(subset=['Democratic', 'Republican'], how='all')
df_8 = df_8.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df_8.head(250))

print('\nNumber of Nulls left:')
display(df_8.isnull().sum())

df_8.to_csv("1964_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12204/1997250428.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_8 = pd.read_html(str(tables8[7]))[0]

,Month,Lyndon B. Johnson (D) %,Barry Goldwater (R) %
0,June,77%,18%
1,June,76%,20%
2,July,62%,26%
3,July,59%,31%
4,August,65%,29%
5,September,65%,29%
6,September,62%,32%
7,October,64%,29%
8,October,64%,36%
9,Actual result,61.05%,38.47%
10,Difference between actual result and final poll,-2.95%,+2.47%

Renamed Columns Table Preview:

                                              Month Democratic Republican
0                                              June        77%        18%
1                                              June        76%        20%
2                                              July        62%        26%
3                                              July        59%        31%
4                                            August        65%        29%
5                                         September        65%        29%
6                                         September        62%        32%
7                                           October        64%        29%
8                                           October        64%        36%
9                                     Actual result     61.05%     38.47%
10  Difference between actual result and final poll     -2.95%     +2.47%

Data Types Before Conversion:

Month         object
Democratic    object
Republican    object
dtype: object

Data Types After Conversion:

Month          object
Democratic    float64
Republican    float64
dtype: object

Table with New Columns:

,Month,Democratic,Republican,Poll_Leading_Margin,Poll_Leader
0,June,77.00,18.00,59.00,0
1,June,76.00,20.00,56.00,0
2,July,62.00,26.00,36.00,0
3,July,59.00,31.00,28.00,0
4,August,65.00,29.00,36.00,0
5,September,65.00,29.00,36.00,0
6,September,62.00,32.00,30.00,0
7,October,64.00,29.00,35.00,0
8,October,64.00,36.00,28.00,0
9,Actual result,61.05,38.47,22.58,0
10,Difference between actual result and final poll,-2.95,2.47,5.42,1

['Month', 'Democratic', 'Republican', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0        77.00       18.00                59.00            0
1        76.00       20.00                56.00            0
2        62.00       26.00                36.00            0
3        59.00       31.00                28.00            0
4        65.00       29.00                36.00            0
5        65.00       29.00                36.00            0
6        62.00       32.00                30.00            0
7        64.00       29.00                35.00            0
8        64.00       36.00                28.00            0
9        61.05       38.47                22.58            0
10       -2.95        2.47                 5.42            1

After Dropping Final Rows (9 & 10):

   Democratic  Republican  Poll_Leading_Margin  Poll_Leader
4        65.0        29.0                 36.0            0
5        65.0        29.0                 36.0            0
6        62.0        32.0                 30.0            0
7        64.0        29.0                 35.0            0
8        64.0        36.0                 28.0            0

Final dtypes:

Democratic             float64
Republican             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

   year  Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0  1964        77.0        18.0                 59.0            0
1  1964        76.0        20.0                 56.0            0
2  1964        62.0        26.0                 36.0            0
3  1964        59.0        31.0                 28.0            0
4  1964        65.0        29.0                 36.0            0
5  1964        65.0        29.0                 36.0            0
6  1964        62.0        32.0                 30.0            0
7  1964        64.0        29.0                 35.0            0
8  1964        64.0        36.0                 28.0            0

Number of Nulls left:

year                   0
Democratic             0
Republican             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64