In [3]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url9 = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#1968"
response9 = requests.get(url9)
soup9 = BeautifulSoup(response9.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response9.status_code}')

# Get all tables in wikitable class
tables9 = soup9.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables9)}')

# Load the 1960 polling table manually by index
df_9 = pd.read_html(str(tables9[8]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df_9.head(250))

# Rename candidate columns for consistency
df_9 = df_9.rename(columns={
    df_9.columns[2]: 'Democratic',
    df_9.columns[1]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df_9.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df_9.dtypes)

# Convert percentage strings to floats
df_9['Democratic'] = df_9['Democratic'].str.replace('%', '').astype(float)
df_9['Republican'] = df_9['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df_9.dtypes)

# Add calculated columns
df_9['Poll_Leading_Margin'] = abs(df_9['Democratic'] - df_9['Republican'])
df_9['Poll_Leader'] = (df_9['Republican'] > df_9['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df_9.head(250))

print(list(df_9.columns))

# Drop the extra columns
df_9 = df_9.drop(columns='Month')
df_9 = df_9.drop(columns=['George Wallace (American Independent)\xa0%'])

print('\nDropped Extra Columns:')
display(df_9.head(250))

# Drop final summary rows (row 12 and 13)
df_9 = df_9.drop(index=[12, 13])
df_9.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (12 & 13):')
display(df_9.tail())

print('\nFinal dtypes:')
display(df_9.dtypes)

# Add year column at the beginning
df_9.insert(0, 'year', 1968)

df_9 = df_9.dropna(subset=['Democratic', 'Republican'], how='all')
df_9 = df_9.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df_9.head(250))

print('\nNumber of Nulls left:')
display(df_9.isnull().sum())

df_9.to_csv("1968_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12270/1489754095.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_9 = pd.read_html(str(tables9[8]))[0]

,Month,Richard Nixon (R) %,Hubert Humphrey (D) %,George Wallace (American Independent) %
0,April,43%,34%,9%
1,May,39%,36%,14%
2,May,36%,42%,14%
3,June,37%,42%,14%
4,July,35%,40%,16%
5,July,40%,38%,16%
6,August,45%,29%,18%
7,September,43%,31%,19%
8,September,43%,28%,21%
9,September,44%,29%,20%
10,October,44%,36%,15%
11,November,43%,42%,15%
12,Actual result,43.42%,42.72%,13.53%
13,Difference between actual result and final poll,+0.42%,+0.72%,-1.47%

Renamed Columns Table Preview:

,Month,Republican,Democratic,George Wallace (American Independent) %
0,April,43%,34%,9%
1,May,39%,36%,14%
2,May,36%,42%,14%
3,June,37%,42%,14%
4,July,35%,40%,16%
5,July,40%,38%,16%
6,August,45%,29%,18%
7,September,43%,31%,19%
8,September,43%,28%,21%
9,September,44%,29%,20%
10,October,44%,36%,15%
11,November,43%,42%,15%
12,Actual result,43.42%,42.72%,13.53%
13,Difference between actual result and final poll,+0.42%,+0.72%,-1.47%

Data Types Before Conversion:

Month                                      object
Republican                                 object
Democratic                                 object
George Wallace (American Independent) %    object
dtype: object

Data Types After Conversion:

Month                                       object
Republican                                 float64
Democratic                                 float64
George Wallace (American Independent) %     object
dtype: object

Table with New Columns:

,Month,Republican,Democratic,George Wallace (American Independent) %,Poll_Leading_Margin,Poll_Leader
0,April,43.00,34.00,9%,9.0,1
1,May,39.00,36.00,14%,3.0,1
2,May,36.00,42.00,14%,6.0,0
3,June,37.00,42.00,14%,5.0,0
4,July,35.00,40.00,16%,5.0,0
5,July,40.00,38.00,16%,2.0,1
6,August,45.00,29.00,18%,16.0,1
7,September,43.00,31.00,19%,12.0,1
8,September,43.00,28.00,21%,15.0,1
9,September,44.00,29.00,20%,15.0,1
10,October,44.00,36.00,15%,8.0,1
11,November,43.00,42.00,15%,1.0,1
12,Actual result,43.42,42.72,13.53%,0.7,1
13,Difference between actual result and final poll,0.42,0.72,-1.47%,0.3,0

['Month', 'Republican', 'Democratic', 'George Wallace (American Independent)\xa0%', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0        43.00       34.00                  9.0            1
1        39.00       36.00                  3.0            1
2        36.00       42.00                  6.0            0
3        37.00       42.00                  5.0            0
4        35.00       40.00                  5.0            0
5        40.00       38.00                  2.0            1
6        45.00       29.00                 16.0            1
7        43.00       31.00                 12.0            1
8        43.00       28.00                 15.0            1
9        44.00       29.00                 15.0            1
10       44.00       36.00                  8.0            1
11       43.00       42.00                  1.0            1
12       43.42       42.72                  0.7            1
13        0.42        0.72                  0.3            0

After Dropping Final Rows (12 & 13):

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
7         43.0        31.0                 12.0            1
8         43.0        28.0                 15.0            1
9         44.0        29.0                 15.0            1
10        44.0        36.0                  8.0            1
11        43.0        42.0                  1.0            1

Final dtypes:

Republican             float64
Democratic             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0   1968        43.0        34.0                  9.0            1
1   1968        39.0        36.0                  3.0            1
2   1968        36.0        42.0                  6.0            0
3   1968        37.0        42.0                  5.0            0
4   1968        35.0        40.0                  5.0            0
5   1968        40.0        38.0                  2.0            1
6   1968        45.0        29.0                 16.0            1
7   1968        43.0        31.0                 12.0            1
8   1968        43.0        28.0                 15.0            1
9   1968        44.0        29.0                 15.0            1
10  1968        44.0        36.0                  8.0            1
11  1968        43.0        42.0                  1.0            1

Number of Nulls left:

year                   0
Republican             0
Democratic             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64