In [2]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#1976"
response = requests.get(url)
soup = BeautifulSoup(response.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response.status_code}')

# Get all tables in wikitable class
tables = soup.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables)}')

# Load the 1976 polling table manually by index
df = pd.read_html(str(tables[10]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df.head(250))

# Rename candidate columns for consistency
df = df.rename(columns={
    df.columns[1]: 'Democratic',
    df.columns[2]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df.dtypes)

# Convert percentage strings to floats
df['Democratic'] = df['Democratic'].str.replace('%', '').astype(float)
df['Republican'] = df['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df.dtypes)

# Add calculated columns
df['Poll_Leading_Margin'] = abs(df['Democratic'] - df['Republican'])
df['Poll_Leader'] = (df['Republican'] > df['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df.head(250))

print(list(df.columns))

# Drop the extra columns
df = df.drop(columns='Month')
#df = df.drop(columns=['George Wallace (American Independent)\xa0%'])

print('\nDropped Extra Columns:')
display(df.head(250))

# Drop final summary rows (row 15 and 16)
df = df.drop(index=[15, 16])
df.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (15 & 16):')
display(df.tail())

print('\nFinal dtypes:')
display(df.dtypes)

# Add year column at the beginning
df.insert(0, 'year', 1976)

df = df.dropna(subset=['Democratic', 'Republican'], how='all')
df = df.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df.head(250))

print('\nNumber of Nulls left:')
display(df.isnull().sum())

df_11 = df

df_11.to_csv("1976_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12366/3071252952.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[10]))[0]

,Month,Jimmy Carter (D) %,Gerald Ford (R) %
0,March,47%,42%
1,March,48%,46%
2,March,48%,46%
3,April,48%,43%
4,May,52%,42%
5,May,53%,40%
6,June,55%,37%
7,June,53%,36%
8,July,62%,29%
9,August,54%,32%
10,August,51%,36%
11,September,51%,40%
12,October,47%,45%
13,October,47%,41%
14,October,48%,49%
15,Actual result,50.08%,48.01%
16,Difference between actual result and final poll,+2.08%,-0.99%

Renamed Columns Table Preview:

                                              Month Democratic Republican
0                                             March        47%        42%
1                                             March        48%        46%
2                                             March        48%        46%
3                                             April        48%        43%
4                                               May        52%        42%
5                                               May        53%        40%
6                                              June        55%        37%
7                                              June        53%        36%
8                                              July        62%        29%
9                                            August        54%        32%
10                                           August        51%        36%
11                                        September        51%        40%
12                                          October        47%        45%
13                                          October        47%        41%
14                                          October        48%        49%
15                                    Actual result     50.08%     48.01%
16  Difference between actual result and final poll     +2.08%     -0.99%

Data Types Before Conversion:

Month         object
Democratic    object
Republican    object
dtype: object

Data Types After Conversion:

Month          object
Democratic    float64
Republican    float64
dtype: object

Table with New Columns:

,Month,Democratic,Republican,Poll_Leading_Margin,Poll_Leader
0,March,47.00,42.00,5.00,0
1,March,48.00,46.00,2.00,0
2,March,48.00,46.00,2.00,0
3,April,48.00,43.00,5.00,0
4,May,52.00,42.00,10.00,0
5,May,53.00,40.00,13.00,0
6,June,55.00,37.00,18.00,0
7,June,53.00,36.00,17.00,0
8,July,62.00,29.00,33.00,0
9,August,54.00,32.00,22.00,0
10,August,51.00,36.00,15.00,0
11,September,51.00,40.00,11.00,0
12,October,47.00,45.00,2.00,0
13,October,47.00,41.00,6.00,0
14,October,48.00,49.00,1.00,1
15,Actual result,50.08,48.01,2.07,0
16,Difference between actual result and final poll,2.08,-0.99,3.07,0

['Month', 'Democratic', 'Republican', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0        47.00       42.00                 5.00            0
1        48.00       46.00                 2.00            0
2        48.00       46.00                 2.00            0
3        48.00       43.00                 5.00            0
4        52.00       42.00                10.00            0
5        53.00       40.00                13.00            0
6        55.00       37.00                18.00            0
7        53.00       36.00                17.00            0
8        62.00       29.00                33.00            0
9        54.00       32.00                22.00            0
10       51.00       36.00                15.00            0
11       51.00       40.00                11.00            0
12       47.00       45.00                 2.00            0
13       47.00       41.00                 6.00            0
14       48.00       49.00                 1.00            1
15       50.08       48.01                 2.07            0
16        2.08       -0.99                 3.07            0

After Dropping Final Rows (15 & 16):

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
10        51.0        36.0                 15.0            0
11        51.0        40.0                 11.0            0
12        47.0        45.0                  2.0            0
13        47.0        41.0                  6.0            0
14        48.0        49.0                  1.0            1

Final dtypes:

Democratic             float64
Republican             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0   1976        47.0        42.0                  5.0            0
1   1976        48.0        46.0                  2.0            0
2   1976        48.0        46.0                  2.0            0
3   1976        48.0        43.0                  5.0            0
4   1976        52.0        42.0                 10.0            0
5   1976        53.0        40.0                 13.0            0
6   1976        55.0        37.0                 18.0            0
7   1976        53.0        36.0                 17.0            0
8   1976        62.0        29.0                 33.0            0
9   1976        54.0        32.0                 22.0            0
10  1976        51.0        36.0                 15.0            0
11  1976        51.0        40.0                 11.0            0
12  1976        47.0        45.0                  2.0            0
13  1976        47.0        41.0                  6.0            0
14  1976        48.0        49.0                  1.0            1

Number of Nulls left:

year                   0
Democratic             0
Republican             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64