In [4]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#1980"
response = requests.get(url)
soup = BeautifulSoup(response.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response.status_code}')

# Get all tables in wikitable class
tables = soup.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables)}')

# Load the 1980 polling table manually by index
df = pd.read_html(str(tables[11]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df.head(250))

# Rename candidate columns for consistency
df = df.rename(columns={
    df.columns[2]: 'Democratic',
    df.columns[1]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df.dtypes)

# Convert percentage strings to floats
df['Democratic'] = df['Democratic'].str.replace('%', '').astype(float)
df['Republican'] = df['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df.dtypes)

# Add calculated columns
df['Poll_Leading_Margin'] = abs(df['Democratic'] - df['Republican'])
df['Poll_Leader'] = (df['Republican'] > df['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df.head(250))

print(list(df.columns))

# Drop the extra columns
df = df.drop(columns='Month')
df = df.drop(columns=['John B. Anderson (I)\xa0%'])

print('\nDropped Extra Columns:')
display(df.head(250))

# Drop final summary rows (row 17 and 18)
df = df.drop(index=[17, 18])
df.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (17 & 18):')
display(df.tail())

print('\nFinal dtypes:')
display(df.dtypes)

# Add year column at the beginning
df.insert(0, 'year', 1980)

df = df.dropna(subset=['Democratic', 'Republican'], how='all')
df = df.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df.head(250))

print('\nNumber of Nulls left:')
display(df.isnull().sum())

df_12 = df

df_12.to_csv("1980_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12390/2543999599.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[11]))[0]

,Month,Ronald Reagan (R) %,Jimmy Carter (D) %,John B. Anderson (I) %
0,December 1979/January 1980,33%,62%,NaN
1,February/March,31%,60%,NaN
2,February/March,33%,58%,NaN
3,February/March,34%,40%,21%
4,April/May,34%,41%,18%
5,April/May,32%,38%,21%
6,April/May,32%,40%,21%
7,June/July,32%,39%,21%
8,June/July,33%,35%,24%
9,June/July,37%,32%,22%
10,June/July,37%,34%,21%
11,August/September,45%,29%,14%
12,August/September,38%,39%,13%
13,August/September,39%,39%,14%
14,October/November,40%,44%,9%
15,October/November,39%,45%,9%
16,October/November,47%,44%,8%
17,Actual result,50.75%,41.01%,6.61%
18,Difference between actual result and final poll,+3.75%,-2.99%,-1.39%

Renamed Columns Table Preview:

,Month,Republican,Democratic,John B. Anderson (I) %
0,December 1979/January 1980,33%,62%,NaN
1,February/March,31%,60%,NaN
2,February/March,33%,58%,NaN
3,February/March,34%,40%,21%
4,April/May,34%,41%,18%
5,April/May,32%,38%,21%
6,April/May,32%,40%,21%
7,June/July,32%,39%,21%
8,June/July,33%,35%,24%
9,June/July,37%,32%,22%
10,June/July,37%,34%,21%
11,August/September,45%,29%,14%
12,August/September,38%,39%,13%
13,August/September,39%,39%,14%
14,October/November,40%,44%,9%
15,October/November,39%,45%,9%
16,October/November,47%,44%,8%
17,Actual result,50.75%,41.01%,6.61%
18,Difference between actual result and final poll,+3.75%,-2.99%,-1.39%

Data Types Before Conversion:

Month                     object
Republican                object
Democratic                object
John B. Anderson (I) %    object
dtype: object

Data Types After Conversion:

Month                      object
Republican                float64
Democratic                float64
John B. Anderson (I) %     object
dtype: object

Table with New Columns:

,Month,Republican,Democratic,John B. Anderson (I) %,Poll_Leading_Margin,Poll_Leader
0,December 1979/January 1980,33.00,62.00,NaN,29.00,0
1,February/March,31.00,60.00,NaN,29.00,0
2,February/March,33.00,58.00,NaN,25.00,0
3,February/March,34.00,40.00,21%,6.00,0
4,April/May,34.00,41.00,18%,7.00,0
5,April/May,32.00,38.00,21%,6.00,0
6,April/May,32.00,40.00,21%,8.00,0
7,June/July,32.00,39.00,21%,7.00,0
8,June/July,33.00,35.00,24%,2.00,0
9,June/July,37.00,32.00,22%,5.00,1
10,June/July,37.00,34.00,21%,3.00,1
11,August/September,45.00,29.00,14%,16.00,1
12,August/September,38.00,39.00,13%,1.00,0
13,August/September,39.00,39.00,14%,0.00,0
14,October/November,40.00,44.00,9%,4.00,0
15,October/November,39.00,45.00,9%,6.00,0
16,October/November,47.00,44.00,8%,3.00,1
17,Actual result,50.75,41.01,6.61%,9.74,1
18,Difference between actual result and final poll,3.75,-2.99,-1.39%,6.74,1

['Month', 'Republican', 'Democratic', 'John B. Anderson (I)\xa0%', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0        33.00       62.00                29.00            0
1        31.00       60.00                29.00            0
2        33.00       58.00                25.00            0
3        34.00       40.00                 6.00            0
4        34.00       41.00                 7.00            0
5        32.00       38.00                 6.00            0
6        32.00       40.00                 8.00            0
7        32.00       39.00                 7.00            0
8        33.00       35.00                 2.00            0
9        37.00       32.00                 5.00            1
10       37.00       34.00                 3.00            1
11       45.00       29.00                16.00            1
12       38.00       39.00                 1.00            0
13       39.00       39.00                 0.00            0
14       40.00       44.00                 4.00            0
15       39.00       45.00                 6.00            0
16       47.00       44.00                 3.00            1
17       50.75       41.01                 9.74            1
18        3.75       -2.99                 6.74            1

After Dropping Final Rows (17 & 18):

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
12        38.0        39.0                  1.0            0
13        39.0        39.0                  0.0            0
14        40.0        44.0                  4.0            0
15        39.0        45.0                  6.0            0
16        47.0        44.0                  3.0            1

Final dtypes:

Republican             float64
Democratic             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0   1980        33.0        62.0                 29.0            0
1   1980        31.0        60.0                 29.0            0
2   1980        33.0        58.0                 25.0            0
3   1980        34.0        40.0                  6.0            0
4   1980        34.0        41.0                  7.0            0
5   1980        32.0        38.0                  6.0            0
6   1980        32.0        40.0                  8.0            0
7   1980        32.0        39.0                  7.0            0
8   1980        33.0        35.0                  2.0            0
9   1980        37.0        32.0                  5.0            1
10  1980        37.0        34.0                  3.0            1
11  1980        45.0        29.0                 16.0            1
12  1980        38.0        39.0                  1.0            0
13  1980        39.0        39.0                  0.0            0
14  1980        40.0        44.0                  4.0            0
15  1980        39.0        45.0                  6.0            0
16  1980        47.0        44.0                  3.0            1

Number of Nulls left:

year                   0
Republican             0
Democratic             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64