In [3]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#2000"
response = requests.get(url)
soup = BeautifulSoup(response.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response.status_code}')

# Get all tables in wikitable class
tables = soup.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables)}')

# Load the 2000 polling table manually by index
df = pd.read_html(str(tables[16]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df.head(250))

# Rename candidate columns for consistency
df = df.rename(columns={
    df.columns[2]: 'Democratic',
    df.columns[1]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df.dtypes)

# Convert percentage strings to floats
df['Democratic'] = df['Democratic'].str.replace('%', '').astype(float)
df['Republican'] = df['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df.dtypes)

# Add calculated columns
df['Poll_Leading_Margin'] = abs(df['Democratic'] - df['Republican'])
df['Poll_Leader'] = (df['Republican'] > df['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df.head(250))

print(list(df.columns))

# Drop the extra columns
df = df.drop(columns='Month')
df = df.drop(columns=['Ralph Nader (Green)\xa0%'])

print('\nDropped Extra Columns:')
display(df.head(250))

# Drop final summary rows (row 40 and 41)
df = df.drop(index=[40, 41])
df.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (40 & 41):')
display(df.tail())

print('\nFinal dtypes:')
display(df.dtypes)

# Add year column at the beginning
df.insert(0, 'year', 2000)

df = df.dropna(subset=['Democratic', 'Republican'], how='all')
df = df.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df.head(250))

print('\nNumber of Nulls left:')
display(df.isnull().sum())

df_17 = df

df_17.to_csv("2000_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12750/1926164259.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[16]))[0]

,Month,George W. Bush (R) %,Al Gore (D) %,Ralph Nader (Green) %
0,April,47%,41%,4%
1,May,NaN,NaN,NaN
2,June,46%,41%,6%
3,June,50%,38%,6%
4,July,45%,43%,5%
5,July,50%,39%,4%
6,August,54%,37%,4%
7,August,55%,39%,2%
8,August,46%,47%,3%
9,August,46%,45%,3%
10,September,44%,47%,3%
11,September,46%,45%,2%
12,September,42%,49%,3%
13,September,41%,49%,4%
14,September,42%,49%,2%
15,September,41%,49%,3%
16,September,44%,48%,2%
17,September,41%,51%,3%
18,September,42%,50%,2%
19,September,47%,44%,2%
20,September,46%,44%,2%
21,September,46%,44%,3%
22,September,45%,45%,4%
23,October,41%,49%,2%
24,October,40%,51%,2%
25,October,48%,41%,4%
26,October,50%,42%,4%
27,October,45%,45%,2%
28,October,45%,45%,3%
29,October,48%,43%,2%
30,October,47%,44%,3%
31,October,51%,40%,4%
32,October,44%,46%,4%
33,October,49%,42%,3%
34,October,52%,39%,4%
35,October,49%,42%,3%
36,October,47%,44%,3%
37,October,47%,43%,4%
38,November,47%,43%,4%
39,November,48%,46%,4%
40,Actual result,47.87%,48.38%,2.74%
41,Difference between actual result and final poll,-0.13%,+2.38%,-1.26%

Renamed Columns Table Preview:

,Month,Republican,Democratic,Ralph Nader (Green) %
0,April,47%,41%,4%
1,May,NaN,NaN,NaN
2,June,46%,41%,6%
3,June,50%,38%,6%
4,July,45%,43%,5%
5,July,50%,39%,4%
6,August,54%,37%,4%
7,August,55%,39%,2%
8,August,46%,47%,3%
9,August,46%,45%,3%
10,September,44%,47%,3%
11,September,46%,45%,2%
12,September,42%,49%,3%
13,September,41%,49%,4%
14,September,42%,49%,2%
15,September,41%,49%,3%
16,September,44%,48%,2%
17,September,41%,51%,3%
18,September,42%,50%,2%
19,September,47%,44%,2%
20,September,46%,44%,2%
21,September,46%,44%,3%
22,September,45%,45%,4%
23,October,41%,49%,2%
24,October,40%,51%,2%
25,October,48%,41%,4%
26,October,50%,42%,4%
27,October,45%,45%,2%
28,October,45%,45%,3%
29,October,48%,43%,2%
30,October,47%,44%,3%
31,October,51%,40%,4%
32,October,44%,46%,4%
33,October,49%,42%,3%
34,October,52%,39%,4%
35,October,49%,42%,3%
36,October,47%,44%,3%
37,October,47%,43%,4%
38,November,47%,43%,4%
39,November,48%,46%,4%
40,Actual result,47.87%,48.38%,2.74%
41,Difference between actual result and final poll,-0.13%,+2.38%,-1.26%

Data Types Before Conversion:

Month                    object
Republican               object
Democratic               object
Ralph Nader (Green) %    object
dtype: object

Data Types After Conversion:

Month                     object
Republican               float64
Democratic               float64
Ralph Nader (Green) %     object
dtype: object

Table with New Columns:

,Month,Republican,Democratic,Ralph Nader (Green) %,Poll_Leading_Margin,Poll_Leader
0,April,47.00,41.00,4%,6.00,1
1,May,NaN,NaN,NaN,NaN,0
2,June,46.00,41.00,6%,5.00,1
3,June,50.00,38.00,6%,12.00,1
4,July,45.00,43.00,5%,2.00,1
5,July,50.00,39.00,4%,11.00,1
6,August,54.00,37.00,4%,17.00,1
7,August,55.00,39.00,2%,16.00,1
8,August,46.00,47.00,3%,1.00,0
9,August,46.00,45.00,3%,1.00,1
10,September,44.00,47.00,3%,3.00,0
11,September,46.00,45.00,2%,1.00,1
12,September,42.00,49.00,3%,7.00,0
13,September,41.00,49.00,4%,8.00,0
14,September,42.00,49.00,2%,7.00,0
15,September,41.00,49.00,3%,8.00,0
16,September,44.00,48.00,2%,4.00,0
17,September,41.00,51.00,3%,10.00,0
18,September,42.00,50.00,2%,8.00,0
19,September,47.00,44.00,2%,3.00,1
20,September,46.00,44.00,2%,2.00,1
21,September,46.00,44.00,3%,2.00,1
22,September,45.00,45.00,4%,0.00,0
23,October,41.00,49.00,2%,8.00,0
24,October,40.00,51.00,2%,11.00,0
25,October,48.00,41.00,4%,7.00,1
26,October,50.00,42.00,4%,8.00,1
27,October,45.00,45.00,2%,0.00,0
28,October,45.00,45.00,3%,0.00,0
29,October,48.00,43.00,2%,5.00,1
30,October,47.00,44.00,3%,3.00,1
31,October,51.00,40.00,4%,11.00,1
32,October,44.00,46.00,4%,2.00,0
33,October,49.00,42.00,3%,7.00,1
34,October,52.00,39.00,4%,13.00,1
35,October,49.00,42.00,3%,7.00,1
36,October,47.00,44.00,3%,3.00,1
37,October,47.00,43.00,4%,4.00,1
38,November,47.00,43.00,4%,4.00,1
39,November,48.00,46.00,4%,2.00,1
40,Actual result,47.87,48.38,2.74%,0.51,0
41,Difference between actual result and final poll,-0.13,2.38,-1.26%,2.51,0

['Month', 'Republican', 'Democratic', 'Ralph Nader (Green)\xa0%', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0        47.00       41.00                 6.00            1
1          NaN         NaN                  NaN            0
2        46.00       41.00                 5.00            1
3        50.00       38.00                12.00            1
4        45.00       43.00                 2.00            1
5        50.00       39.00                11.00            1
6        54.00       37.00                17.00            1
7        55.00       39.00                16.00            1
8        46.00       47.00                 1.00            0
9        46.00       45.00                 1.00            1
10       44.00       47.00                 3.00            0
11       46.00       45.00                 1.00            1
12       42.00       49.00                 7.00            0
13       41.00       49.00                 8.00            0
14       42.00       49.00                 7.00            0
15       41.00       49.00                 8.00            0
16       44.00       48.00                 4.00            0
17       41.00       51.00                10.00            0
18       42.00       50.00                 8.00            0
19       47.00       44.00                 3.00            1
20       46.00       44.00                 2.00            1
21       46.00       44.00                 2.00            1
22       45.00       45.00                 0.00            0
23       41.00       49.00                 8.00            0
24       40.00       51.00                11.00            0
25       48.00       41.00                 7.00            1
26       50.00       42.00                 8.00            1
27       45.00       45.00                 0.00            0
28       45.00       45.00                 0.00            0
29       48.00       43.00                 5.00            1
30       47.00       44.00                 3.00            1
31       51.00       40.00                11.00            1
32       44.00       46.00                 2.00            0
33       49.00       42.00                 7.00            1
34       52.00       39.00                13.00            1
35       49.00       42.00                 7.00            1
36       47.00       44.00                 3.00            1
37       47.00       43.00                 4.00            1
38       47.00       43.00                 4.00            1
39       48.00       46.00                 2.00            1
40       47.87       48.38                 0.51            0
41       -0.13        2.38                 2.51            0

After Dropping Final Rows (40 & 41):

    Republican  Democratic  Poll_Leading_Margin  Poll_Leader
35        49.0        42.0                  7.0            1
36        47.0        44.0                  3.0            1
37        47.0        43.0                  4.0            1
38        47.0        43.0                  4.0            1
39        48.0        46.0                  2.0            1

Final dtypes:

Republican             float64
Democratic             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Republican  Democratic  Poll_Leading_Margin  Poll_Leader
0   2000        47.0        41.0                  6.0            1
1   2000        46.0        41.0                  5.0            1
2   2000        50.0        38.0                 12.0            1
3   2000        45.0        43.0                  2.0            1
4   2000        50.0        39.0                 11.0            1
5   2000        54.0        37.0                 17.0            1
6   2000        55.0        39.0                 16.0            1
7   2000        46.0        47.0                  1.0            0
8   2000        46.0        45.0                  1.0            1
9   2000        44.0        47.0                  3.0            0
10  2000        46.0        45.0                  1.0            1
11  2000        42.0        49.0                  7.0            0
12  2000        41.0        49.0                  8.0            0
13  2000        42.0        49.0                  7.0            0
14  2000        41.0        49.0                  8.0            0
15  2000        44.0        48.0                  4.0            0
16  2000        41.0        51.0                 10.0            0
17  2000        42.0        50.0                  8.0            0
18  2000        47.0        44.0                  3.0            1
19  2000        46.0        44.0                  2.0            1
20  2000        46.0        44.0                  2.0            1
21  2000        45.0        45.0                  0.0            0
22  2000        41.0        49.0                  8.0            0
23  2000        40.0        51.0                 11.0            0
24  2000        48.0        41.0                  7.0            1
25  2000        50.0        42.0                  8.0            1
26  2000        45.0        45.0                  0.0            0
27  2000        45.0        45.0                  0.0            0
28  2000        48.0        43.0                  5.0            1
29  2000        47.0        44.0                  3.0            1
30  2000        51.0        40.0                 11.0            1
31  2000        44.0        46.0                  2.0            0
32  2000        49.0        42.0                  7.0            1
33  2000        52.0        39.0                 13.0            1
34  2000        49.0        42.0                  7.0            1
35  2000        47.0        44.0                  3.0            1
36  2000        47.0        43.0                  4.0            1
37  2000        47.0        43.0                  4.0            1
38  2000        48.0        46.0                  2.0            1

Number of Nulls left:

year                   0
Republican             0
Democratic             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64