In [4]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#2008"
response = requests.get(url)
soup = BeautifulSoup(response.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response.status_code}')

# Get all tables in wikitable class
tables = soup.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables)}')

# Load the 2008 polling table manually by index
df = pd.read_html(str(tables[18]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df.head(250))

# Rename candidate columns for consistency
df = df.rename(columns={
    df.columns[1]: 'Democratic',
    df.columns[2]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df.dtypes)

# Convert percentage strings to floats
df['Democratic'] = df['Democratic'].str.replace('%', '').astype(float)
df['Republican'] = df['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df.dtypes)

# Add calculated columns
df['Poll_Leading_Margin'] = abs(df['Democratic'] - df['Republican'])
df['Poll_Leader'] = (df['Republican'] > df['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df.head(250))

print(list(df.columns))

# Drop the extra columns
df = df.drop(columns='Month')
#df = df.drop(columns=['Ralph Nader (Green)\xa0%'])

print('\nDropped Extra Columns:')
display(df.head(250))

# Drop final summary rows (row 24 and 25)
df = df.drop(index=[24, 25])
df.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (24 & 25):')
display(df.tail())

print('\nFinal dtypes:')
display(df.dtypes)

# Add year column at the beginning
df.insert(0, 'year', 2008)

df = df.dropna(subset=['Democratic', 'Republican'], how='all')
df = df.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df.head(250))

print('\nNumber of Nulls left:')
display(df.isnull().sum())

df_19 = df

df_19.to_csv("2008_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12839/4276877369.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[18]))[0]

,Month,Barack Obama (D) %,John McCain (R) %
0,March,46%,44%
1,March,43%,47%
2,April,46%,43%
3,April,45%,45%
4,May,42%,48%
5,May,47%,43%
6,May,44%,47%
7,June,48%,41%
8,June,45%,45%
9,July,48%,42%
10,July,45%,44%
11,July,49%,40%
12,July,44%,44%
13,August,48%,42%
14,August,45%,45%
15,August,50%,42%
16,September,44%,49%
17,September,50%,44%
18,September,46%,46%
19,October,52%,41%
20,October,49%,43%
21,October,52%,42%
22,October,53%,40%
23,October,53%,42%
24,Actual result,52.86%,45.60%
25,Difference between actual result and final poll,-0.14%,+3.60%

Renamed Columns Table Preview:

                                              Month Democratic Republican
0                                             March        46%        44%
1                                             March        43%        47%
2                                             April        46%        43%
3                                             April        45%        45%
4                                               May        42%        48%
5                                               May        47%        43%
6                                               May        44%        47%
7                                              June        48%        41%
8                                              June        45%        45%
9                                              July        48%        42%
10                                             July        45%        44%
11                                             July        49%        40%
12                                             July        44%        44%
13                                           August        48%        42%
14                                           August        45%        45%
15                                           August        50%        42%
16                                        September        44%        49%
17                                        September        50%        44%
18                                        September        46%        46%
19                                          October        52%        41%
20                                          October        49%        43%
21                                          October        52%        42%
22                                          October        53%        40%
23                                          October        53%        42%
24                                    Actual result     52.86%     45.60%
25  Difference between actual result and final poll     -0.14%     +3.60%

Data Types Before Conversion:

Month         object
Democratic    object
Republican    object
dtype: object

Data Types After Conversion:

Month          object
Democratic    float64
Republican    float64
dtype: object

Table with New Columns:

,Month,Democratic,Republican,Poll_Leading_Margin,Poll_Leader
0,March,46.00,44.0,2.00,0
1,March,43.00,47.0,4.00,1
2,April,46.00,43.0,3.00,0
3,April,45.00,45.0,0.00,0
4,May,42.00,48.0,6.00,1
5,May,47.00,43.0,4.00,0
6,May,44.00,47.0,3.00,1
7,June,48.00,41.0,7.00,0
8,June,45.00,45.0,0.00,0
9,July,48.00,42.0,6.00,0
10,July,45.00,44.0,1.00,0
11,July,49.00,40.0,9.00,0
12,July,44.00,44.0,0.00,0
13,August,48.00,42.0,6.00,0
14,August,45.00,45.0,0.00,0
15,August,50.00,42.0,8.00,0
16,September,44.00,49.0,5.00,1
17,September,50.00,44.0,6.00,0
18,September,46.00,46.0,0.00,0
19,October,52.00,41.0,11.00,0
20,October,49.00,43.0,6.00,0
21,October,52.00,42.0,10.00,0
22,October,53.00,40.0,13.00,0
23,October,53.00,42.0,11.00,0
24,Actual result,52.86,45.6,7.26,0
25,Difference between actual result and final poll,-0.14,3.6,3.74,1

['Month', 'Democratic', 'Republican', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0        46.00        44.0                 2.00            0
1        43.00        47.0                 4.00            1
2        46.00        43.0                 3.00            0
3        45.00        45.0                 0.00            0
4        42.00        48.0                 6.00            1
5        47.00        43.0                 4.00            0
6        44.00        47.0                 3.00            1
7        48.00        41.0                 7.00            0
8        45.00        45.0                 0.00            0
9        48.00        42.0                 6.00            0
10       45.00        44.0                 1.00            0
11       49.00        40.0                 9.00            0
12       44.00        44.0                 0.00            0
13       48.00        42.0                 6.00            0
14       45.00        45.0                 0.00            0
15       50.00        42.0                 8.00            0
16       44.00        49.0                 5.00            1
17       50.00        44.0                 6.00            0
18       46.00        46.0                 0.00            0
19       52.00        41.0                11.00            0
20       49.00        43.0                 6.00            0
21       52.00        42.0                10.00            0
22       53.00        40.0                13.00            0
23       53.00        42.0                11.00            0
24       52.86        45.6                 7.26            0
25       -0.14         3.6                 3.74            1

After Dropping Final Rows (24 & 25):

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
19        52.0        41.0                 11.0            0
20        49.0        43.0                  6.0            0
21        52.0        42.0                 10.0            0
22        53.0        40.0                 13.0            0
23        53.0        42.0                 11.0            0

Final dtypes:

Democratic             float64
Republican             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0   2008        46.0        44.0                  2.0            0
1   2008        43.0        47.0                  4.0            1
2   2008        46.0        43.0                  3.0            0
3   2008        45.0        45.0                  0.0            0
4   2008        42.0        48.0                  6.0            1
5   2008        47.0        43.0                  4.0            0
6   2008        44.0        47.0                  3.0            1
7   2008        48.0        41.0                  7.0            0
8   2008        45.0        45.0                  0.0            0
9   2008        48.0        42.0                  6.0            0
10  2008        45.0        44.0                  1.0            0
11  2008        49.0        40.0                  9.0            0
12  2008        44.0        44.0                  0.0            0
13  2008        48.0        42.0                  6.0            0
14  2008        45.0        45.0                  0.0            0
15  2008        50.0        42.0                  8.0            0
16  2008        44.0        49.0                  5.0            1
17  2008        50.0        44.0                  6.0            0
18  2008        46.0        46.0                  0.0            0
19  2008        52.0        41.0                 11.0            0
20  2008        49.0        43.0                  6.0            0
21  2008        52.0        42.0                 10.0            0
22  2008        53.0        40.0                 13.0            0
23  2008        53.0        42.0                 11.0            0

Number of Nulls left:

year                   0
Democratic             0
Republican             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64