In [2]:
# Consolidated into one code block to make it easier to scrape data for project. 
# Each print statement should allow me to see the output as it is running, incase any changes or tweaks need to be made. 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Load the Wiki page
url = "https://en.wikipedia.org/wiki/Polling_for_United_States_presidential_elections#2012"
response = requests.get(url)
soup = BeautifulSoup(response.content)

# Status of request
print(f'Status Code of Wikipedia site is: {response.status_code}')

# Get all tables in wikitable class
tables = soup.find_all("table", class_="wikitable")
print(f'Number of tables is: {len(tables)}')

# Load the 2012 polling table manually by index
df = pd.read_html(str(tables[19]))[0]

# Show raw table
print('\nRaw Table Preview:')
display(df.head(250))

# Rename candidate columns for consistency
df = df.rename(columns={
    df.columns[1]: 'Democratic',
    df.columns[2]: 'Republican'
})

print('\nRenamed Columns Table Preview:')
display(df.head(250))

# Show data types before conversion
print('\nData Types Before Conversion:')
display(df.dtypes)

# Convert percentage strings to floats
df['Democratic'] = df['Democratic'].str.replace('%', '').astype(float)
df['Republican'] = df['Republican'].str.replace('%', '').astype(float)

# Show data types after conversion
print('\nData Types After Conversion:')
display(df.dtypes)

# Add calculated columns
df['Poll_Leading_Margin'] = abs(df['Democratic'] - df['Republican'])
df['Poll_Leader'] = (df['Republican'] > df['Democratic']).astype(int)

print('\nTable with New Columns:')
display(df.head(250))

print(list(df.columns))

# Drop the extra columns
df = df.drop(columns='Month')
#df = df.drop(columns=['Ralph Nader (Green)\xa0%'])

print('\nDropped Extra Columns:')
display(df.head(250))

# Drop final summary rows (row 32 and 33)
df = df.drop(index=[32, 33])
df.reset_index(drop=True, inplace=True)

print('\nAfter Dropping Final Rows (32 & 33):')
display(df.tail())

print('\nFinal dtypes:')
display(df.dtypes)

# Add year column at the beginning
df.insert(0, 'year', 2012)

df = df.dropna(subset=['Democratic', 'Republican'], how='all')
df = df.reset_index(drop=True)

print('\nFinal Table with Year Column:')
display(df.head(250))

print('\nNumber of Nulls left:')
display(df.isnull().sum())

df_20 = df

df_20.to_csv("2012_Opinion_Polling_Data_cleaned.csv", index=False)

Status Code of Wikipedia site is: 200
Number of tables is: 23

Raw Table Preview:

/var/folders/t1/nb2p0ppn0t1fldv4wgzvfrtw0000gn/T/ipykernel_12864/1913341786.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables[19]))[0]

,Month,Barack Obama (D) %,Mitt Romney (R) %
0,February,48%,44%
1,February,49%,43%
2,February,49%,44%
3,March,47%,45%
4,March,48%,44%
5,April,48%,43%
6,April,49%,43%
7,April,47%,44%
8,April,48%,44%
9,May,47%,44%
10,May,46%,46%
11,May,47%,45%
12,May,46%,44%
13,June,48%,45%
14,June,46%,45%
15,June,47%,44%
16,July,46%,45%
17,July,47%,45%
18,July,46%,45%
19,July,47%,45%
20,August,48%,44%
21,August,47%,45%
22,August,47%,46%
23,September,47%,47%
24,September,49%,45%
25,September,48%,45%
26,September,49%,45%
27,October,49%,46%
28,October,47%,48%
29,October,47%,47%
30,October,47%,48%
31,November,49%,48%
32,Actual result,51.01%,47.15%
33,Difference between actual result and final poll,+2.01%,-0.85%

Renamed Columns Table Preview:

                                              Month Democratic Republican
0                                          February        48%        44%
1                                          February        49%        43%
2                                          February        49%        44%
3                                             March        47%        45%
4                                             March        48%        44%
5                                             April        48%        43%
6                                             April        49%        43%
7                                             April        47%        44%
8                                             April        48%        44%
9                                               May        47%        44%
10                                              May        46%        46%
11                                              May        47%        45%
12                                              May        46%        44%
13                                             June        48%        45%
14                                             June        46%        45%
15                                             June        47%        44%
16                                             July        46%        45%
17                                             July        47%        45%
18                                             July        46%        45%
19                                             July        47%        45%
20                                           August        48%        44%
21                                           August        47%        45%
22                                           August        47%        46%
23                                        September        47%        47%
24                                        September        49%        45%
25                                        September        48%        45%
26                                        September        49%        45%
27                                          October        49%        46%
28                                          October        47%        48%
29                                          October        47%        47%
30                                          October        47%        48%
31                                         November        49%        48%
32                                    Actual result     51.01%     47.15%
33  Difference between actual result and final poll     +2.01%     -0.85%

Data Types Before Conversion:

Month         object
Democratic    object
Republican    object
dtype: object

Data Types After Conversion:

Month          object
Democratic    float64
Republican    float64
dtype: object

Table with New Columns:

,Month,Democratic,Republican,Poll_Leading_Margin,Poll_Leader
0,February,48.00,44.00,4.00,0
1,February,49.00,43.00,6.00,0
2,February,49.00,44.00,5.00,0
3,March,47.00,45.00,2.00,0
4,March,48.00,44.00,4.00,0
5,April,48.00,43.00,5.00,0
6,April,49.00,43.00,6.00,0
7,April,47.00,44.00,3.00,0
8,April,48.00,44.00,4.00,0
9,May,47.00,44.00,3.00,0
10,May,46.00,46.00,0.00,0
11,May,47.00,45.00,2.00,0
12,May,46.00,44.00,2.00,0
13,June,48.00,45.00,3.00,0
14,June,46.00,45.00,1.00,0
15,June,47.00,44.00,3.00,0
16,July,46.00,45.00,1.00,0
17,July,47.00,45.00,2.00,0
18,July,46.00,45.00,1.00,0
19,July,47.00,45.00,2.00,0
20,August,48.00,44.00,4.00,0
21,August,47.00,45.00,2.00,0
22,August,47.00,46.00,1.00,0
23,September,47.00,47.00,0.00,0
24,September,49.00,45.00,4.00,0
25,September,48.00,45.00,3.00,0
26,September,49.00,45.00,4.00,0
27,October,49.00,46.00,3.00,0
28,October,47.00,48.00,1.00,1
29,October,47.00,47.00,0.00,0
30,October,47.00,48.00,1.00,1
31,November,49.00,48.00,1.00,0
32,Actual result,51.01,47.15,3.86,0
33,Difference between actual result and final poll,2.01,-0.85,2.86,0

['Month', 'Democratic', 'Republican', 'Poll_Leading_Margin', 'Poll_Leader']

Dropped Extra Columns:

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0        48.00       44.00                 4.00            0
1        49.00       43.00                 6.00            0
2        49.00       44.00                 5.00            0
3        47.00       45.00                 2.00            0
4        48.00       44.00                 4.00            0
5        48.00       43.00                 5.00            0
6        49.00       43.00                 6.00            0
7        47.00       44.00                 3.00            0
8        48.00       44.00                 4.00            0
9        47.00       44.00                 3.00            0
10       46.00       46.00                 0.00            0
11       47.00       45.00                 2.00            0
12       46.00       44.00                 2.00            0
13       48.00       45.00                 3.00            0
14       46.00       45.00                 1.00            0
15       47.00       44.00                 3.00            0
16       46.00       45.00                 1.00            0
17       47.00       45.00                 2.00            0
18       46.00       45.00                 1.00            0
19       47.00       45.00                 2.00            0
20       48.00       44.00                 4.00            0
21       47.00       45.00                 2.00            0
22       47.00       46.00                 1.00            0
23       47.00       47.00                 0.00            0
24       49.00       45.00                 4.00            0
25       48.00       45.00                 3.00            0
26       49.00       45.00                 4.00            0
27       49.00       46.00                 3.00            0
28       47.00       48.00                 1.00            1
29       47.00       47.00                 0.00            0
30       47.00       48.00                 1.00            1
31       49.00       48.00                 1.00            0
32       51.01       47.15                 3.86            0
33        2.01       -0.85                 2.86            0

After Dropping Final Rows (32 & 33):

    Democratic  Republican  Poll_Leading_Margin  Poll_Leader
27        49.0        46.0                  3.0            0
28        47.0        48.0                  1.0            1
29        47.0        47.0                  0.0            0
30        47.0        48.0                  1.0            1
31        49.0        48.0                  1.0            0

Final dtypes:

Democratic             float64
Republican             float64
Poll_Leading_Margin    float64
Poll_Leader              int64
dtype: object

Final Table with Year Column:

    year  Democratic  Republican  Poll_Leading_Margin  Poll_Leader
0   2012        48.0        44.0                  4.0            0
1   2012        49.0        43.0                  6.0            0
2   2012        49.0        44.0                  5.0            0
3   2012        47.0        45.0                  2.0            0
4   2012        48.0        44.0                  4.0            0
5   2012        48.0        43.0                  5.0            0
6   2012        49.0        43.0                  6.0            0
7   2012        47.0        44.0                  3.0            0
8   2012        48.0        44.0                  4.0            0
9   2012        47.0        44.0                  3.0            0
10  2012        46.0        46.0                  0.0            0
11  2012        47.0        45.0                  2.0            0
12  2012        46.0        44.0                  2.0            0
13  2012        48.0        45.0                  3.0            0
14  2012        46.0        45.0                  1.0            0
15  2012        47.0        44.0                  3.0            0
16  2012        46.0        45.0                  1.0            0
17  2012        47.0        45.0                  2.0            0
18  2012        46.0        45.0                  1.0            0
19  2012        47.0        45.0                  2.0            0
20  2012        48.0        44.0                  4.0            0
21  2012        47.0        45.0                  2.0            0
22  2012        47.0        46.0                  1.0            0
23  2012        47.0        47.0                  0.0            0
24  2012        49.0        45.0                  4.0            0
25  2012        48.0        45.0                  3.0            0
26  2012        49.0        45.0                  4.0            0
27  2012        49.0        46.0                  3.0            0
28  2012        47.0        48.0                  1.0            1
29  2012        47.0        47.0                  0.0            0
30  2012        47.0        48.0                  1.0            1
31  2012        49.0        48.0                  1.0            0

Number of Nulls left:

year                   0
Democratic             0
Republican             0
Poll_Leading_Margin    0
Poll_Leader            0
dtype: int64